[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "media_acquisition_scripts"
version = "0.1.0"
description = ""
readme = "README.md"

requires-python = ">=3.9"
dependencies = [
    "qobuz_dl",
    "rapidfuzz",
    "music_tag",
]